apiVersion: v1
kind: ConfigMap
metadata:
  name: easyshop-config
  namespace: easyshop
data:
  MONGODB_URI: "mongodb://mongodb-service:27017/easyshop"
  NODE_ENV: "production"
  NEXT_PUBLIC_API_URL: "https://easyshop.adtechs.xyz/api"
  NEXTAUTH_URL: "https://easyshop.adtechs.xyz/"
  NEXTAUTH_SECRET: "hk4/SZvmfSgUsbKHMnWafbWdktNZxdfmAlyIdMyx2aA="
  JWT_SECRET: "97c83b41e952b761b7652d4467393341759595499757ade4b546292625348572"
